name = "Vault Hunters"
author = "ModogTheDev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03f5a30943b939d9977fff9afd3c1f13728763bd4b331bf4a23e110bac6070ce"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
