name = "Vault Hunters"
author = "ModogTheDev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f23fdf1fadfb96c0835215adf9a8b34938ac2567e88d505d0c3dad8b66507fb6"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
