name = "Vault Hunters"
author = "ModogTheDev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e820bd062e183fc02f78412ef8d946ae3b4814c73dfbc6053c3c921df548f57e"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
